version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: task_manager_db
    environment:
      - POSTGRES_USER=task_manager
      - POSTGRES_PASSWORD=task_manager
      - POSTGRES_DB=task_manager
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  task_manager:
    build: .
    container_name: task_manager_app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/task_manager
      - SPRING_DATASOURCE_USERNAME=task_manager
      - SPRING_DATASOURCE_PASSWORD=task_manager
      - SPRING_FLYWAY_URL=jdbc:postgresql://postgres:5432/task_manager
      - SPRING_FLYWAY_USER=task_manager
      - SPRING_FLYWAY_PASSWORD=task_manager
    ports:
      - '8080:8080'
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
